# -*- coding: utf-8 -*-
"""SA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kRiVaD0r4vCqu0noHKDYISc5rGpBLpY
"""

import pandas as pd
df = pd.read_csv("/content/Reviews.csv", encoding='ISO-8859-1')

print(df.head())

#Since we are working on sentiment analysis, we will only keep the Score and Text columns.

df = df[['Score', 'Text']]
df.head()

# Check for missing values
print(df.isnull().sum())

def assign_sentiment(score):
    if score >= 4:
        return "positive"
    elif score == 3:
        return "neutral"
    else:
        return "negative"

df['Sentiment'] = df['Score'].apply(assign_sentiment)

# Display the dataset with the new Sentiment column
print(df.head())

import nltk
from nltk.corpus import stopwords

# Download stopwords
nltk.download('stopwords')

# Load English stopwords
stop_words = set(stopwords.words('english'))

import re

def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation and special characters
    text = " ".join(word for word in text.split() if word not in stop_words)  # Remove stopwords
    return text

df['Cleaned_Text'] = df['Text'].apply(clean_text)

# Display first few cleaned reviews
print(df[['Text', 'Cleaned_Text']].head())

df.info()

from sklearn.model_selection import train_test_split

# Split data
X_train, X_test, y_train, y_test = train_test_split(df['Cleaned_Text'], df['Sentiment'], test_size=0.2, random_state=42)

# Print dataset size
print(f"Training data size: {len(X_train)}")
print(f"Testing data size: {len(X_test)}")

from sklearn.feature_extraction.text import TfidfVectorizer

# Convert text into numerical features using TF-IDF
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Print shape of transformed data
print("Shape of TF-IDF transformed data:", X_train_tfidf.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Train Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_tfidf, y_train)

# Predict and evaluate
y_pred_lr = lr_model.predict(X_test_tfidf)
lr_accuracy = accuracy_score(y_test, y_pred_lr)
print(f"Logistic Regression Accuracy: {lr_accuracy:.4f}")

from sklearn.naive_bayes import MultinomialNB

# Train Naive Bayes model
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

# Predict and evaluate
y_pred_nb = nb_model.predict(X_test_tfidf)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
print(f"Naive Bayes Accuracy: {nb_accuracy:.4f}")

# Store accuracies in a dictionary
model_accuracies = {
    "Logistic Regression": lr_accuracy,
    "Naive Bayes": nb_accuracy,

}

# Find the best model
best_model_name = max(model_accuracies, key=model_accuracies.get)
best_model_accuracy = model_accuracies[best_model_name]

print("\nBest Model:", best_model_name)
print("Best Accuracy:", best_model_accuracy)

import joblib

# Save the selected model and TF-IDF vectorizer
joblib.dump(best_model_name, "sentiment_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Best Model and TF-IDF Vectorizer saved successfully!")

import streamlit as st
import joblib

# Load the saved model and vectorizer
model = joblib.load("/content/sentiment_model.pkl")
vectorizer = joblib.load("/content/tfidf_vectorizer.pkl")

# Streamlit App
st.title("📝 Sentiment Analysis App")
st.write("Enter a product review, and the model will predict its sentiment.")

# Text input for user review
user_review = st.text_area("Enter your review here:")

if st.button("Analyze Sentiment"):
    if user_review.strip() == "":
        st.warning("Please enter a review to analyze.")
    else:
        # Transform user input
        review_tfidf = vectorizer.transform([user_review])

        # Predict sentiment
        prediction = model.predict(review_tfidf)[0]

        # Display the result
        st.success(f"Predicted Sentiment: **{prediction}**")