# -*- coding: utf-8 -*-
"""SAapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEgNbhg-I67ZP6UI6CBiVAEQE135WBzO
"""

pip install streamlit

import streamlit as st
import joblib

# Load the saved model and vectorizer
model = joblib.load("/content/sentiment_model.pkl")
vectorizer = joblib.load("/content/tfidf_vectorizer.pkl")

# Streamlit App
st.title("📝 Sentiment Analysis App")
st.write("Enter a product review, and the model will predict its sentiment.")

# Text input for user review
user_review = st.text_area("Enter your review here:")

if st.button("Analyze Sentiment"):
    if user_review.strip() == "":
        st.warning("Please enter a review to analyze.")
    else:
        # Transform user input
        review_tfidf = vectorizer.transform([user_review])

        # Predict sentiment
        prediction = model.predict(review_tfidf)[0]

        # Display the result
        st.success(f"Predicted Sentiment: **{prediction}**")